In [1]:
import numpy as np
import pandas as pd

In [2]:
filename = 'Gaussian_similarity_dataframe_172062.csv'
df = pd.read_csv(filename)

In [3]:
df

source_images_idx  source_i  source_j  source_k  \
0                       0         0         0         0   
1                       0         0         0         5   
2                       0         0         0        10   
3                       0         0         0        15   
4                       0         0         0        20   
...                   ...       ...       ...       ...   
172057                 15       256       256        16   
172058                 15       256       256        20   
172059                 15       256       256        24   
172060                 15       256       256        28   
172061                 15       256       256        32   

                                                    means  \
0       [[ 0.46554034  1.84369587 -0.08983612 -0.09219...   
1       [[ 0.45754175  1.84865482 -0.09555791 -0.09197...   
2       [[ 0.40841618  1.84711304 -0.09149587 -0.07988...   
3       [[ 0.36879455  1.85962435 -0.09248569 -0.07358...   
4       [[ 0.34487718  1.87042186 -0.09005267 -0.07299...   
...                                                   ...   
172057  [[ 0.55292116  1.77903703 -0.07796942 -0.06656...   
172058  [[ 0.56689376  1.77102271 -0.0822784  -0.07209...   
172059  [[ 0.57290224  1.7633751  -0.08878428 -0.07618...   
172060  [[ 0.5641183   1.76888947 -0.09151133 -0.07697...   
172061  [[ 0.55668705  1.77348059 -0.09760489 -0.07753...   

                                                     covs  \
0       [[[ 1.35053131e+00 -6.64606251e-01 -5.49150645...   
1       [[[ 1.31243511e+00 -6.53424577e-01 -6.37958458...   
2       [[[ 1.16743229e+00 -6.44741187e-01 -5.56220666...   
3       [[[ 1.09453895e+00 -6.21332804e-01 -5.76768178...   
4       [[[ 1.05991918e+00 -6.17144724e-01 -5.37120947...   
...                                                   ...   
172057  [[[ 1.27858232e+00 -6.91365301e-01 -4.83839229...   
172058  [[[ 1.27572008e+00 -6.96104294e-01 -5.11402591...   
172059  [[[ 1.21017864e+00 -6.73280779e-01 -4.95331401...   
172060  [[[ 1.14631334e+00 -6.43771217e-01 -4.72323690...   
172061  [[[ 1.11919228e+00 -6.33572479e-01 -5.02362209...   

                                  label_frequency  \
0       [2090160    6930      62       0       0]   
1       [2075876   21214      62       0       0]   
2       [2054106   42984      62       0       0]   
3       [2027535   69555      62       0       0]   
4       [2001466   95624      62       0       0]   
...                                           ...   
172057  [1998072      26       0   40342   58712]   
172058  [2009306      26       0   31912   55908]   
172059  [2023176      26       0   22918   51032]   
172060  [2036964      26       0   15190   44972]   
172061  [2051512      26       0    8120   37494]   

                                perdict_frequency  
0       [2086418       0       0       0       0]  
1       [2066037    2859       0       0       0]  
2       [2031980   18392       0       0       0]  
3       [2004972   36085       0       0       0]  
4       [1969931   59123       0       0       0]  
...                                           ...  
172057  [1953316       0       0   25277    2237]  
172058  [1967622       0       0   18684    6033]  
172059  [1986153       0       0   12814    5576]  
172060  [2011173       0       0    8093    6142]  
172061  [2030113       0       0    2010    2999]  

[172062 rows x 8 columns]

In [13]:
df[df['source_images_idx'] == 2]

source_images_idx  source_i  source_j  source_k  \
21780                  2         0         0         0   
21781                  2         0         0         3   
21782                  2         0         0         6   
21783                  2         0         0         9   
21784                  2         0         0        12   
...                  ...       ...       ...       ...   
32665                  2       256       256        15   
32666                  2       256       256        18   
32667                  2       256       256        21   
32668                  2       256       256        24   
32669                  2       256       256        27   

                                                   means  \
21780  [[ 0.54298187  1.8071078  -0.09952586 -0.08910...   
21781  [[ 0.4912381   1.82826183 -0.09849099 -0.08056...   
21782  [[ 0.45288109  1.83982798 -0.09754357 -0.07816...   
21783  [[ 0.44520731  1.84366003 -0.09618054 -0.08203...   
21784  [[ 0.42726346  1.84504617 -0.09148028 -0.08075...   
...                                                  ...   
32665  [[ 0.35723601  1.85621589 -0.07646501 -0.05366...   
32666  [[ 0.3781117   1.84591984 -0.07543052 -0.05586...   
32667  [[ 0.38641356  1.84183064 -0.077106   -0.05987...   
32668  [[ 0.39885625  1.8308493  -0.08243384 -0.05941...   
32669  [[ 0.42101615  1.82068255 -0.09125214 -0.05877...   

                                                    covs  \
21780  [[[ 1.57723978e+00 -7.75835179e-01 -9.84216560...   
21781  [[[ 1.42032871e+00 -7.08643176e-01 -8.69956908...   
21782  [[[ 1.32183992e+00 -6.81708315e-01 -7.84887753...   
21783  [[[ 1.25776266e+00 -6.57270219e-01 -7.09517797...   
21784  [[[ 1.17445682 -0.63868015 -0.05876994 -0.0341...   
...                                                  ...   
32665  [[[ 0.99169644 -0.60162553 -0.03138995 -0.0172...   
32666  [[[ 1.02836441e+00 -6.17961659e-01 -3.22162810...   
32667  [[[ 1.04104710e+00 -6.23082934e-01 -3.49276582...   
32668  [[[ 1.06343549e+00 -6.32535402e-01 -4.30618323...   
32669  [[[ 1.09983114e+00 -6.46195783e-01 -5.64049363...   

                                 label_frequency  \
21780  [2032700   55288    9164       0       0]   
21781  [2007160   80828    9164       0       0]   
21782  [1978358  109630    9164       0       0]   
21783  [1949929  138418    8805       0       0]   
21784  [1923844  166102    7206       0       0]   
...                                          ...   
32665  [2015595       2       0   34676   46879]   
32666  [2015010       4       0   31614   50524]   
32667  [2019497       4       0   27127   50524]   
32668  [2024824       4       0   21800   50524]   
32669  [2031442       4       0   15182   50524]   

                               perdict_frequency  
21780  [2008469   32961    3663       0       0]  
21781  [1979279   51214    3759       0       0]  
21782  [1946128   77295    3533       0       0]  
21783  [1919023  101777    3273       0       0]  
21784  [1890647  126274    2415       0       0]  
...                                          ...  
32665  [1988443       0       0   19392   13183]  
32666  [1985731       0       0   16659   12121]  
32667  [1986453       0       0   14223   13369]  
32668  [1992222       0       0    9985   12943]  
32669  [1997887       0       0    5861   13532]  

[10890 rows x 8 columns]

In [14]:
df[df['source_images_idx'] == 3]

source_images_idx  source_i  source_j  source_k  \
32670                  3         0         0         0   
32671                  3         0         0         2   
32672                  3         0         0         4   
32673                  3         0         0         6   
32674                  3         0         0         8   
...                  ...       ...       ...       ...   
44644                  3       256       256        12   
44645                  3       256       256        14   
44646                  3       256       256        16   
44647                  3       256       256        18   
44648                  3       256       256        20   

                                                   means  \
32670  [[ 0.58825514  1.78758236 -0.10118449 -0.09816...   
32671  [[ 0.57192726  1.79174786 -0.09850528 -0.09310...   
32672  [[ 0.55916387  1.79928971 -0.09561719 -0.09327...   
32673  [[ 0.53738857  1.80843712 -0.09406689 -0.09275...   
32674  [[ 0.52397529  1.81058519 -0.09611805 -0.09160...   
...                                                  ...   
44644  [[ 0.44843832  1.81966334 -0.06621628 -0.06448...   
44645  [[ 0.44565161  1.82245378 -0.06949854 -0.06607...   
44646  [[ 0.43349266  1.82706162 -0.06905389 -0.06628...   
44647  [[ 0.42718657  1.82691033 -0.06885016 -0.06690...   
44648  [[ 0.41769721  1.83196689 -0.06659895 -0.06746...   

                                                    covs  \
32670  [[[ 1.77420857e+00 -8.48565208e-01 -1.24414120...   
32671  [[[ 1.65745342e+00 -8.10980582e-01 -1.12251743...   
32672  [[[ 1.58118812 -0.77336841 -0.10096969 -0.0906...   
32673  [[[ 1.48403710e+00 -7.30329408e-01 -8.63375231...   
32674  [[[ 1.41654427e+00 -7.13098877e-01 -8.39767005...   
...                                                  ...   
44644  [[[ 1.11672693e+00 -6.43508311e-01 -2.18122387...   
44645  [[[ 1.14515182e+00 -6.53998974e-01 -3.09721277...   
44646  [[[ 1.12902823 -0.65043189 -0.02803054 -0.0351...   
44647  [[[ 1.13083852e+00 -6.57919117e-01 -2.51027977...   
44648  [[[ 1.09447691 -0.64075457 -0.01765481 -0.0379...   

                                 label_frequency  \
32670  [2033456   63696       0       0       0]   
32671  [2013852   83300       0       0       0]   
32672  [1994694  102458       0       0       0]   
32673  [1974248  122904       0       0       0]   
32674  [1952808  144344       0       0       0]   
...                                          ...   
44644  [1971488       0       0   51854   73810]   
44645  [1964728       0       0   48812   83612]   
44646  [1960440       0       0   44816   91896]   
44647  [1959690       0       0   40186   97276]   
44648  [1963702       0       0   35396   98054]   

                               perdict_frequency  
32670  [2003134   30106       0       0       0]  
32671  [1980970   43075       0       0       0]  
32672  [1958015   59441       0       0       0]  
32673  [1934682   78312       0       0       0]  
32674  [1910042   92571       0       0       0]  
...                                          ...  
44644  [1921416       0       0   33458   25988]  
44645  [1915259       0       0   31083   27332]  
44646  [1910043       0       0   27696   27229]  
44647  [1910101       0       0   23992   26712]  
44648  [1910741       0       0   20787   30710]  

[11979 rows x 8 columns]

In [6]:
df['source_images_idx'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
df['source_i'].unique()

array([  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96,
       104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200,
       208, 216, 224, 232, 240, 248, 256])

In [8]:
df['source_j'].unique()

array([  0,   8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96,
       104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200,
       208, 216, 224, 232, 240, 248, 256])

In [9]:
df['source_k'].unique()

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40,  2,  4,  6,  8, 12, 14, 16, 18,
        3,  9, 21, 24, 27, 28, 32])

In [10]:
len(df['source_i'].unique())

33

In [11]:
len(df['source_j'].unique())

33

In [12]:
len(df['source_k'].unique())

24